services:
  web:
    build: .
    volumes:
      - .:/app
    expose:
      - "8000"  # Expose port to other services (not host)

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map host port 80 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use your nginx config
    depends_on:
      - web
